plugins:
  mailgun_spam_detection:
    client: false
    type: enum
    default: "flag"
    choices:
      - "flag"
      - "none"
      - "score"

  mailgun_spam_score:
    client: false
    default: 5.0
    min: -20.0
    max: 25.0

  dkim_domain_exclusions:
    client: false
    default: ""
    type: list
    list_type: simple

  spf_domain_exclusions:
    client: false
    default: ""
    type: list
    list_type: simple

  mailgun_blocked_domains:
    client: false
    default: ""
    type: list
    list_type: simple

  mailgun_log_rejections:
    client: false
    default: false
